// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc6ve6jeS5cNAiyZTx6M_m6eyDkTqTjfI',
    appId: '1:391973598755:web:e9cc61a4040b8b0a5aa396',
    messagingSenderId: '391973598755',
    projectId: 'pacman-school',
    authDomain: 'pacman-school.firebaseapp.com',
    databaseURL: 'https://pacman-school-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pacman-school.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-i3m8tWc91L3hzah7_vnD1_S1i64DKG8',
    appId: '1:391973598755:android:c6f9cb7212f42c115aa396',
    messagingSenderId: '391973598755',
    projectId: 'pacman-school',
    databaseURL: 'https://pacman-school-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pacman-school.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvNmv5jLcj-cn0QncdPhnxhHQgJgOH0Vs',
    appId: '1:391973598755:ios:b0e1a292883162275aa396',
    messagingSenderId: '391973598755',
    projectId: 'pacman-school',
    databaseURL: 'https://pacman-school-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pacman-school.firebasestorage.app',
    iosBundleId: 'com.example.pacmanApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvNmv5jLcj-cn0QncdPhnxhHQgJgOH0Vs',
    appId: '1:391973598755:ios:b0e1a292883162275aa396',
    messagingSenderId: '391973598755',
    projectId: 'pacman-school',
    databaseURL: 'https://pacman-school-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pacman-school.firebasestorage.app',
    iosBundleId: 'com.example.pacmanApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc6ve6jeS5cNAiyZTx6M_m6eyDkTqTjfI',
    appId: '1:391973598755:web:a57414f7160afb765aa396',
    messagingSenderId: '391973598755',
    projectId: 'pacman-school',
    authDomain: 'pacman-school.firebaseapp.com',
    databaseURL: 'https://pacman-school-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pacman-school.firebasestorage.app',
  );
}
