@startuml
set namespaceSeparator ::

class "pacman_application::database::firebase_options.dart::DefaultFirebaseOptions" {
  {static} +FirebaseOptions android
  {static} +FirebaseOptions ios
  {static} +FirebaseOptions macos
  {static} +FirebaseOptions web
  {static} +FirebaseOptions windows
  {static} +FirebaseOptions currentPlatform
}

"pacman_application::database::firebase_options.dart::DefaultFirebaseOptions" o-- "firebase_core_platform_interface::firebase_core_platform_interface.dart::FirebaseOptions"

class "pacman_application::database::game_user.dart::GameUser" {
  +String uid
  +String name
  +String email
  +Map<BonusType, int> bonusTable
  -int _highScore
  +int highScore
  +int hashCode
  +bool haveInitialized()
  +void addBonus()
  -void _updateScore()
  -void _updateBonusTable()
  -void _setData()
  -dynamic _getBonusEntry()
  +bool ==()
  +String toString()
}

abstract class "pacman_application::game::animation::animated_character.dart::AnimatedCharacter" {
  +String name
  +double x
  +double y
  +Direction currentDirection
  +Direction nextDirection
  +List<SpriteAnimation> animations
  +SpriteAnimation currentAnimation
  +GameManager gameManager
  +Widget getSprite()
  +void update()
  +void reset()
  +void move()
  +void updateAnimation()
  +GameMap getGameMap()
  +GameScreen getGameScreen()
  +Pacman getPacman()
}

"pacman_application::game::animation::animated_character.dart::AnimatedCharacter" o-- "pacman_application::game::direction.dart::Direction"
"pacman_application::game::animation::animated_character.dart::AnimatedCharacter" o-- "pacman_application::game::animation::sprite_animation.dart::SpriteAnimation"
"pacman_application::game::animation::animated_character.dart::AnimatedCharacter" o-- "pacman_application::game::game_manager.dart::GameManager"

class "pacman_application::game::animation::sprite_animation.dart::SpriteAnimation" {
  +String characterName
  +String animationName
  +int spritesAmount
  +double frameSpeed
  +bool isLoop
  -List<String> _paths
  -double _clock
  -int _currentIndex
  -bool _started
  +bool isDone
  +bool isPaused
  +Image getImage()
  +void update()
  +void idle()
}

class "pacman_application::game::bonus.dart::Bonus" {
  +GameManager gameManager
  +double x
  +double y
  +bool isVisible
  +BonusType currentType
  +void Function(BonusType)? onEaten
  {static} +String bonusAssetsPath
  {static} +String bonusesAssetsEndFile
  -Random _random
  +void setVisible()
  +void update()
  +Widget getSprite()
  -Pacman _getPacman()
}

"pacman_application::game::bonus.dart::Bonus" o-- "pacman_application::game::game_manager.dart::GameManager"
"pacman_application::game::bonus.dart::Bonus" o-- "pacman_application::utils::bonus_type.dart::BonusType"
"pacman_application::game::bonus.dart::Bonus" o-- "null::void Function(BonusType)"
"pacman_application::game::bonus.dart::Bonus" o-- "dart::math::Random"

class "pacman_application::game::controller::controller.dart::Controller" {
  +void Function(Direction) onDirectionChanged
  +State<Controller> createState()
}

"pacman_application::game::controller::controller.dart::Controller" o-- "null::void Function(Direction)"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::game::controller::controller.dart::Controller"

class "pacman_application::game::controller::controller.dart::_ControllerState" {
  +Widget build()
  -Widget _buildDpad()
}

"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::game::controller::controller.dart::_ControllerState"

class "pacman_application::game::controller::dpad_button.dart::DpadButton" {
  +double size
  +IconData icon
  +void Function() onPressed
  +State<DpadButton> createState()
}

"pacman_application::game::controller::dpad_button.dart::DpadButton" o-- "flutter::src::widgets::icon_data.dart::IconData"
"pacman_application::game::controller::dpad_button.dart::DpadButton" o-- "dart::ui::void Function()"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::game::controller::dpad_button.dart::DpadButton"

class "pacman_application::game::controller::dpad_button.dart::_DpadButtonState" {
  -bool _isPressed
  -Timer? _repeatTimer
  -void _startPress()
  -void _endPress()
  +void dispose()
  +Widget build()
}

"pacman_application::game::controller::dpad_button.dart::_DpadButtonState" o-- "dart::async::Timer"
"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::game::controller::dpad_button.dart::_DpadButtonState"

class "pacman_application::game::controller::end_game_buttons.dart::EndGameButtons" {
  +double size
  +void Function() onRetry
  +void Function() onExit
  +State<EndGameButtons> createState()
}

"pacman_application::game::controller::end_game_buttons.dart::EndGameButtons" o-- "dart::ui::void Function()"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::game::controller::end_game_buttons.dart::EndGameButtons"

class "pacman_application::game::controller::end_game_buttons.dart::_EndGameButtonsState" {
  -bool _isRetryPressed
  -bool _isExitPressed
  -void _startRetryPress()
  -void _endRetryPress()
  -void _startExitPress()
  -void _endExitPress()
  +Widget build()
  -Widget _buildButton()
}

"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::game::controller::end_game_buttons.dart::_EndGameButtonsState"

class "pacman_application::game::direction.dart::Direction" {
  +int index
  {static} +List<Direction> values
  {static} +Direction up
  {static} +Direction down
  {static} +Direction left
  {static} +Direction right
}

"pacman_application::game::direction.dart::Direction" o-- "pacman_application::game::direction.dart::Direction"
"dart::core::Enum" <|-- "pacman_application::game::direction.dart::Direction"

class "pacman_application::game::dot.dart::Dot" {
  +int x
  +int y
  -bool _isEaten
  +void Function() onEaten
  +void checkIfEaten()
  +void reset()
  +Widget showOnStack()
  -void _eat()
  +Widget build()
}

"pacman_application::game::dot.dart::Dot" o-- "null::void Function()"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pacman_application::game::dot.dart::Dot"

class "pacman_application::game::game_manager.dart::GameManager" {
  +int score
  +int highScore
  +int screenNum
  +int nextGhostEatenScore
  +int lives
  +bool isPaused
  +bool isGameOver
  -bool _hasTriggeredNextScreen
  +GameMap gameMap
  +Pacman pacman
  +List<Ghost> ghosts
  +Bonus bonus
  +List<BonusType> bonusesTaken
  +double dt
  -List<GameTimer> _gameTimers
  -GameTimer _bonusTimer
  -Timer _periodicTimer
  -Stopwatch _stopwatch
  -double _lastTickTime
  +Controller controller
  +EndGameButtons endGameButtons
  +GameScreen currentScreen
  -Widget Function(double) _gameMessage
  +void Function(int) onGameOver
  +void Function() onRetry
  +void Function() onExit
  +void Function(BonusType) onGettingBonus
  -int Function()? _getHighScoreCallback
  -AudioPlayer _audioPlayer
  -_AudioState _currentAudioState
  +void initGame()
  -void _update()
  -void _onDotEaten()
  -void _onSuperDotEaten()
  -void _onBonusEaten()
  -void _onDeath()
  -void _onGhostEaten()
  -void _triggerGameOver()
}

"pacman_application::game::game_manager.dart::GameManager" o-- "pacman_application::game::map::game_map.dart::GameMap"
"pacman_application::game::game_manager.dart::GameManager" o-- "pacman_application::game::pacman.dart::Pacman"
"pacman_application::game::game_manager.dart::GameManager" o-- "pacman_application::game::bonus.dart::Bonus"
"pacman_application::game::game_manager.dart::GameManager" o-- "pacman_application::game::game_timer.dart::GameTimer"
"pacman_application::game::game_manager.dart::GameManager" o-- "dart::async::Timer"
"pacman_application::game::game_manager.dart::GameManager" o-- "pacman_application::game::controller::controller.dart::Controller"
"pacman_application::game::game_manager.dart::GameManager" o-- "pacman_application::game::controller::end_game_buttons.dart::EndGameButtons"
"pacman_application::game::game_manager.dart::GameManager" o-- "pacman_application::game::game_screen.dart::GameScreen"
"pacman_application::game::game_manager.dart::GameManager" o-- "null::Widget Function(double)"
"pacman_application::game::game_manager.dart::GameManager" o-- "null::void Function(int)"
"pacman_application::game::game_manager.dart::GameManager" o-- "null::void Function()"
"pacman_application::game::game_manager.dart::GameManager" o-- "null::void Function(BonusType)"
"pacman_application::game::game_manager.dart::GameManager" o-- "null::int Function()"
"pacman_application::game::game_manager.dart::GameManager" o-- "audioplayers::src::audioplayer.dart::AudioPlayer"
"pacman_application::game::game_manager.dart::GameManager" o-- "pacman_application::game::game_manager.dart::_AudioState"

class "pacman_application::game::game_manager.dart::_AudioState" {
  +int index
  {static} +List<_AudioState> values
  {static} +_AudioState idle
  {static} +_AudioState normal
  {static} +_AudioState blue
  {static} +_AudioState eye
}

"pacman_application::game::game_manager.dart::_AudioState" o-- "pacman_application::game::game_manager.dart::_AudioState"
"dart::core::Enum" <|-- "pacman_application::game::game_manager.dart::_AudioState"

class "pacman_application::game::game_screen.dart::GameScreen" {
  +GameMap gameMap
  +Pacman pacman
  +List<Ghost> ghosts
  +Bonus bonus
  +List<BonusType> bonusesTaken
  +Widget Function(double) gameMessage
  +Controller controller
  +EndGameButtons endGameButtons
  +int Function() getScore
  +int Function() getLives
  +int Function() getHighScore
  +bool Function() isGameOver
  +double dt
  +State<GameScreen> createState()
}

"pacman_application::game::game_screen.dart::GameScreen" o-- "pacman_application::game::map::game_map.dart::GameMap"
"pacman_application::game::game_screen.dart::GameScreen" o-- "pacman_application::game::pacman.dart::Pacman"
"pacman_application::game::game_screen.dart::GameScreen" o-- "pacman_application::game::bonus.dart::Bonus"
"pacman_application::game::game_screen.dart::GameScreen" o-- "null::Widget Function(double)"
"pacman_application::game::game_screen.dart::GameScreen" o-- "pacman_application::game::controller::controller.dart::Controller"
"pacman_application::game::game_screen.dart::GameScreen" o-- "pacman_application::game::controller::end_game_buttons.dart::EndGameButtons"
"pacman_application::game::game_screen.dart::GameScreen" o-- "null::int Function()"
"pacman_application::game::game_screen.dart::GameScreen" o-- "null::bool Function()"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::game::game_screen.dart::GameScreen"

class "pacman_application::game::game_screen.dart::_GameScreenState" {
  -Timer? _uiTimer
  -Color? _pacmanColor
  -Color? _blinkyColor
  -Color? _pinkyColor
  -Color? _inkyColor
  -Color? _clydeColor
  -Color? _mapColor
  +void initState()
  +void dispose()
  +Widget build()
  -Widget _buildHud()
  -Widget _buildScoreColumn()
  -Widget _buildLivesIndicator()
  -Widget _buildBonusStrip()
  -dynamic _loadCustomColors()
  -Color? _getGhostColor()
}

"pacman_application::game::game_screen.dart::_GameScreenState" o-- "dart::async::Timer"
"pacman_application::game::game_screen.dart::_GameScreenState" o-- "dart::ui::Color"
"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::game::game_screen.dart::_GameScreenState"

class "pacman_application::game::game_timer.dart::GameTimer" {
  +double duration
  +void Function()? onEnd
  +bool isLoop
  -double _clock
  +bool isOn
  +void update()
  +void start()
  +void pause()
  -void _reset()
}

"pacman_application::game::game_timer.dart::GameTimer" o-- "null::void Function()"

class "pacman_application::game::ghosts::blinky.dart::Blinky" {
  +String name
  +double x
  +double y
  +dynamic startingPosition
  +Direction currentDirection
  +Direction nextDirection
  +dynamic scatterLocation
  +SpriteAnimation idleAnimation
  +dynamic late()
  +void chase()
}

"pacman_application::game::ghosts::blinky.dart::Blinky" o-- "pacman_application::game::direction.dart::Direction"
"pacman_application::game::ghosts::blinky.dart::Blinky" o-- "pacman_application::game::animation::sprite_animation.dart::SpriteAnimation"
"pacman_application::game::ghosts::ghost.dart::Ghost" <|-- "pacman_application::game::ghosts::blinky.dart::Blinky"

class "pacman_application::game::ghosts::clyde.dart::Clyde" {
  +String name
  +double x
  +double y
  +dynamic startingPosition
  +Direction currentDirection
  +Direction nextDirection
  +dynamic scatterLocation
  +SpriteAnimation idleAnimation
  +dynamic late()
  +void chase()
}

"pacman_application::game::ghosts::clyde.dart::Clyde" o-- "pacman_application::game::direction.dart::Direction"
"pacman_application::game::ghosts::clyde.dart::Clyde" o-- "pacman_application::game::animation::sprite_animation.dart::SpriteAnimation"
"pacman_application::game::ghosts::ghost.dart::Ghost" <|-- "pacman_application::game::ghosts::clyde.dart::Clyde"

abstract class "pacman_application::game::ghosts::ghost.dart::Ghost" {
  +dynamic startingPosition
  +dynamic scatterLocation
  +GhostState state
  +double speed
  +bool hasStartedFrightenedMode
  +void Function()? onDeath
  +void Function()? onEaten
  -SpriteAnimation _up
  -SpriteAnimation _right
  -SpriteAnimation _down
  -SpriteAnimation _left
  -SpriteAnimation _eatenUp
  -SpriteAnimation _eatenRight
  -SpriteAnimation _eatenDown
  -SpriteAnimation _eatenLeft
  -SpriteAnimation _frightened0
  -SpriteAnimation _frightened1
  -SpriteAnimation? _currentEyesAnimation
  -Random _random
  +SpriteAnimation idleAnimation
  +SpriteAnimation up
  +SpriteAnimation right
  +SpriteAnimation down
  +SpriteAnimation left
  +List<SpriteAnimation> animations
  +dynamic abstract()
  +dynamic abstract()
  +void chase()
  +Widget getSprite()
  +void move()
  +void updateAnimation()
  +void update()
  +void reset()
  +void scatter()
  +void frightened()
  +void eaten()
  +void updateState()
  +void stepForward()
  +Direction? ghostChase()
  +Direction? simpleChase()
  +Direction? complexChase()
}

"pacman_application::game::ghosts::ghost.dart::Ghost" o-- "pacman_application::game::ghosts::ghost.dart::GhostState"
"pacman_application::game::ghosts::ghost.dart::Ghost" o-- "null::void Function()"
"pacman_application::game::ghosts::ghost.dart::Ghost" o-- "pacman_application::game::animation::sprite_animation.dart::SpriteAnimation"
"pacman_application::game::ghosts::ghost.dart::Ghost" o-- "dart::math::Random"
"pacman_application::game::animation::animated_character.dart::AnimatedCharacter" <|-- "pacman_application::game::ghosts::ghost.dart::Ghost"

class "pacman_application::game::ghosts::ghost.dart::GhostState" {
  +int index
  {static} +List<GhostState> values
  {static} +GhostState chase
  {static} +GhostState scatter
  {static} +GhostState frightened0
  {static} +GhostState frightened1
  {static} +GhostState eaten
  {static} +GhostState idle
}

"pacman_application::game::ghosts::ghost.dart::GhostState" o-- "pacman_application::game::ghosts::ghost.dart::GhostState"
"dart::core::Enum" <|-- "pacman_application::game::ghosts::ghost.dart::GhostState"

class "pacman_application::game::ghosts::inky.dart::Inky" {
  +String name
  +double x
  +double y
  +dynamic startingPosition
  +Direction currentDirection
  +Direction nextDirection
  +dynamic scatterLocation
  {static} +double blinkyPosition
  +SpriteAnimation idleAnimation
  +dynamic late()
  {static} +void setBlinkyPosition()
  +void chase()
}

"pacman_application::game::ghosts::inky.dart::Inky" o-- "pacman_application::game::direction.dart::Direction"
"pacman_application::game::ghosts::inky.dart::Inky" o-- "pacman_application::game::animation::sprite_animation.dart::SpriteAnimation"
"pacman_application::game::ghosts::ghost.dart::Ghost" <|-- "pacman_application::game::ghosts::inky.dart::Inky"

class "pacman_application::game::ghosts::pinky.dart::Pinky" {
  +String name
  +double x
  +double y
  +dynamic startingPosition
  +Direction currentDirection
  +Direction nextDirection
  +dynamic scatterLocation
  +SpriteAnimation idleAnimation
  +void chase()
}

"pacman_application::game::ghosts::pinky.dart::Pinky" o-- "pacman_application::game::direction.dart::Direction"
"pacman_application::game::ghosts::pinky.dart::Pinky" o-- "pacman_application::game::animation::sprite_animation.dart::SpriteAnimation"
"pacman_application::game::ghosts::ghost.dart::Ghost" <|-- "pacman_application::game::ghosts::pinky.dart::Pinky"

class "pacman_application::game::map::game_map.dart::GameMap" {
  {static} +int kEmpty
  {static} +int kWall
  {static} +int kSmallDot
  {static} +int kSuperDot
  {static} +int kBonus
  {static} +int kTunnel
  {static} +int kGhostHouseDoor
  {static} +int kGhostHouseInterior
  {static} +int kStartingPosition
  +int kCols
  +int kRows
  +double startingX
  +double startingY
  +int ghostHouseX
  +int ghostHouseY
  +double bonusX
  +double bonusY
  +String mapAssetPath
  +List<List<int>> map
  +List<Dot> dots
  +List<SuperDot> superDots
  +int remainingDots
  +void Function() onDotEaten
  +void Function() onSuperDotEaten
  +void reset()
  +bool isWall()
  -void _init()
}

"pacman_application::game::map::game_map.dart::GameMap" o-- "null::void Function()"

class "pacman_application::game::map::map_paller.dart::MapPalette" {
  +GameMap gameMap
  +Widget build()
  -double _computeTileSize()
}

"pacman_application::game::map::map_paller.dart::MapPalette" o-- "pacman_application::game::map::game_map.dart::GameMap"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pacman_application::game::map::map_paller.dart::MapPalette"

class "pacman_application::game::map::maze_painter.dart::MazePainter" {
  +GameMap gameMap
  {static} -Color _wallColor
  {static} -Color _smallDotColor
  {static} -Color _superDotColor
  {static} -Color _bonusColor
  {static} -Color _tunnelColor
  {static} -Color _ghostHouseDoorColor
  {static} -Color _ghostHouseInteriorColor
  {static} -Color _startingPositionColor
  +void paint()
  +bool shouldRepaint()
  -void _paintTile()
  -void _drawRect()
  -void _drawCircle()
}

"pacman_application::game::map::maze_painter.dart::MazePainter" o-- "pacman_application::game::map::game_map.dart::GameMap"
"pacman_application::game::map::maze_painter.dart::MazePainter" o-- "dart::ui::Color"
"flutter::src::rendering::custom_paint.dart::CustomPainter" <|-- "pacman_application::game::map::maze_painter.dart::MazePainter"

class "pacman_application::game::pacman.dart::Pacman" {
  {static} -String _kName
  {static} -double _kSpeed
  +String name
  +Direction currentDirection
  +Direction nextDirection
  +double x
  +double y
  -SpriteAnimation _deathAnimation
  -SpriteAnimation _idleAnimation
  -SpriteAnimation _upAnimation
  -SpriteAnimation _rightAnimation
  -SpriteAnimation _downAnimation
  -SpriteAnimation _leftAnimation
  +List<SpriteAnimation> animations
  +void playDeath()
  +void updateDeathAnimation()
  +Widget nextDirectionArrow()
  +void move()
  +void updateAnimation()
  +void reset()
}

"pacman_application::game::pacman.dart::Pacman" o-- "pacman_application::game::direction.dart::Direction"
"pacman_application::game::pacman.dart::Pacman" o-- "pacman_application::game::animation::sprite_animation.dart::SpriteAnimation"
"pacman_application::game::animation::animated_character.dart::AnimatedCharacter" <|-- "pacman_application::game::pacman.dart::Pacman"

class "pacman_application::game::super_dot.dart::SuperDot" {
  +int x
  +int y
  -bool _isEaten
  +void Function() onEaten
  +void checkIfEaten()
  +void reset()
  +Widget showOnStack()
  -void _eat()
  +Widget build()
}

"pacman_application::game::super_dot.dart::SuperDot" o-- "null::void Function()"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pacman_application::game::super_dot.dart::SuperDot"

class "pacman_application::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "pacman_application::main.dart::MyApp"

class "pacman_application::screens::collectables_screen.dart::CollectablesScreen" {
  +State<CollectablesScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::screens::collectables_screen.dart::CollectablesScreen"

class "pacman_application::screens::collectables_screen.dart::CollectablesScreenState" {
  +void dispose()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::screens::collectables_screen.dart::CollectablesScreenState"

class "pacman_application::screens::home_screen.dart::HomeScreen" {
  +State<HomeScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::screens::home_screen.dart::HomeScreen"

class "pacman_application::screens::home_screen.dart::HomeScreenState" {
  -double _progress
  -AudioPlayer _audioPlayer
  +void initState()
  +void dispose()
  +Widget build()
  -void _computeBonusProgress()
}

"pacman_application::screens::home_screen.dart::HomeScreenState" o-- "audioplayers::src::audioplayer.dart::AudioPlayer"
"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::screens::home_screen.dart::HomeScreenState"

class "pacman_application::screens::leaderboard_screen.dart::LeaderboardScreen" {
  +State<LeaderboardScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::screens::leaderboard_screen.dart::LeaderboardScreen"

class "pacman_application::screens::leaderboard_screen.dart::LeaderboardScreenState" {
  -List<GameUser> _users
  +void initState()
  +void dispose()
  +Widget build()
  -void _loadUsers()
  -Widget _rankBadge()
}

"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::screens::leaderboard_screen.dart::LeaderboardScreenState"

class "pacman_application::screens::login.dart::Login" {
  +State<Login> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::screens::login.dart::Login"

class "pacman_application::screens::login.dart::LoginState" {
  -TextEditingController _emailController
  -TextEditingController _passwordController
  -bool _googleLoading
  +void initState()
  +void dispose()
  +Widget build()
  -void _checkPrefs()
  -dynamic _bonusEntryFromPrefs()
  -void _savePrefs()
  -void _removePrefs()
  -void _signInWithGoogle()
}

"pacman_application::screens::login.dart::LoginState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::screens::login.dart::LoginState"

class "pacman_application::screens::read_me.dart::ReadMe" {
  +State<ReadMe> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::screens::read_me.dart::ReadMe"

class "pacman_application::screens::read_me.dart::ReadMeState" {
  +WebViewController controller
  +void dispose()
  +Widget build()
}

"pacman_application::screens::read_me.dart::ReadMeState" o-- "webview_flutter::src::webview_controller.dart::WebViewController"
"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::screens::read_me.dart::ReadMeState"

class "pacman_application::screens::settings.dart::Settings" {
  +State<Settings> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::screens::settings.dart::Settings"

class "pacman_application::screens::settings.dart::SettingsState" {
  -Color _pacmanColor
  -Color _blinkyColor
  -Color _pinkyColor
  -Color _inkyColor
  -Color _clydeColor
  -Color _mapColor
  +void initState()
  +void dispose()
  +Widget build()
  -void _loadColors()
  -Color? _readColorPrefs()
  -int _floatToInt8()
  -Color _getCharacterColor()
  -void _saveColor()
  -void _showColorDialog()
  -void _resetPacmanColor()
  -void _resetBlinkyColor()
  -void _resetPinkyColor()
  -void _resetInkyColor()
  -void _resetClydeColor()
  -void _resetMapColor()
  -void _resetColor()
  -Widget _colorPickerRow()
}

"pacman_application::screens::settings.dart::SettingsState" o-- "dart::ui::Color"
"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::screens::settings.dart::SettingsState"

class "pacman_application::screens::signup.dart::Signup" {
  +State<Signup> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::screens::signup.dart::Signup"

class "pacman_application::screens::signup.dart::_SignupState" {
  -bool _acceptedTerms
  -bool _isGoogleLoading
  -String _message
  -TextEditingController _nameController
  -TextEditingController _emailController
  -TextEditingController _passwordController
  -bool _canContinue
  +void dispose()
  -dynamic _saveUserPreferences()
  -dynamic _isNewUser()
  -Map<String, int> _createDefaultBonusTable()
  -dynamic _createDatabaseUser()
  -dynamic _setCurrentUser()
  -void _goToLoginScreen()
  -dynamic _signUpWithGoogle()
  -dynamic _signUpWithEmail()
  -Widget _buildInputField()
  -Widget _buildGoogleButton()
  +Widget build()
}

"pacman_application::screens::signup.dart::_SignupState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::screens::signup.dart::_SignupState"

class "pacman_application::utils::appbar.dart::Appbar" {
  +BuildContext context
  +Text header
  +bool canLogout
  +Widget? title
  +List<Widget>? actions
  +double? elevation
  +ShapeBorder? shape
  -void _clearPrefs()
}

"pacman_application::utils::appbar.dart::Appbar" o-- "flutter::src::widgets::framework.dart::BuildContext"
"pacman_application::utils::appbar.dart::Appbar" o-- "flutter::src::widgets::text.dart::Text"
"pacman_application::utils::appbar.dart::Appbar" o-- "flutter::src::widgets::framework.dart::Widget"
"pacman_application::utils::appbar.dart::Appbar" o-- "flutter::src::painting::borders.dart::ShapeBorder"
"flutter::src::material::app_bar.dart::AppBar" <|-- "pacman_application::utils::appbar.dart::Appbar"

class "pacman_application::utils::bonus_card.dart::BonusCard" {
  +int i
  +State<BonusCard> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::utils::bonus_card.dart::BonusCard"

class "pacman_application::utils::bonus_card.dart::BonusCardState" {
  {static} -String _assetDir
  {static} -String _assetExt
  -bool _isPressed
  -bool _isTimerFinished
  -BonusType _bonus
  -bool _hasCollected
  -int _collectedCount
  +void initState()
  +Widget build()
  -void _showBonusDialog()
  -Image _bonusImage()
  -Widget _bonusImageWithGlow()
}

"pacman_application::utils::bonus_card.dart::BonusCardState" o-- "pacman_application::utils::bonus_type.dart::BonusType"
"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::utils::bonus_card.dart::BonusCardState"

class "pacman_application::utils::bonus_type.dart::BonusType" {
  +int index
  {static} +List<BonusType> values
  {static} +BonusType apple
}

"pacman_application::utils::bonus_type.dart::BonusType" o-- "pacman_application::utils::bonus_type.dart::BonusType"
"dart::core::Enum" <|-- "pacman_application::utils::bonus_type.dart::BonusType"

class "pacman_application::utils::game_displayer.dart::GameDisplayer" {
  +State<GameDisplayer> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::utils::game_displayer.dart::GameDisplayer"

class "pacman_application::utils::game_displayer.dart::GameDisplayerState" {
  -GameManager _gameManager
  -GameManager _nextGame
  -AudioPlayer _audioPlayer
  +void initState()
  +void dispose()
  +Widget build()
  -GameManager _buildGameManager()
  -void _onGameOver()
  -void _onRetry()
  -void _onExit()
  -void _onBonusCollected()
}

"pacman_application::utils::game_displayer.dart::GameDisplayerState" o-- "pacman_application::game::game_manager.dart::GameManager"
"pacman_application::utils::game_displayer.dart::GameDisplayerState" o-- "audioplayers::src::audioplayer.dart::AudioPlayer"
"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::utils::game_displayer.dart::GameDisplayerState"

class "pacman_application::utils::loading_screen.dart::LoadingScreen" {
  +State<LoadingScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::utils::loading_screen.dart::LoadingScreen"

class "pacman_application::utils::loading_screen.dart::LoadingScreenState" {
  -Timer _timer
  +void initState()
  +void dispose()
  +Widget build()
}

"pacman_application::utils::loading_screen.dart::LoadingScreenState" o-- "dart::async::Timer"
"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::utils::loading_screen.dart::LoadingScreenState"

class "pacman_application::utils::sidebar.dart::Sidebar" {
  +State<Sidebar> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "pacman_application::utils::sidebar.dart::Sidebar"

class "pacman_application::utils::sidebar.dart::SidebarState" {
  +Widget build()
  -Widget _navRow()
}

"flutter::src::widgets::framework.dart::State" <|-- "pacman_application::utils::sidebar.dart::SidebarState"


@enduml