name: pacman_application
description: "Pacman Android Edition"
publish_to: 'none' 

version: 3.1.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.6.0
  firebase_core: ^4.7.0
  flutterfire_cli: ^1.0.0
  firebase_database: ^12.3.0
  google_sign_in: ^6.2.1
  firebase_auth: ^6.4.0
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.5
  flutter_colorpicker: ^1.1.0
  google_fonts: ^8.1.0
  just_audio: ^0.10.5
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/Full Logo Gif.gif
    - assets/logo/Full Logo.png
    - assets/logo/icon.gif
    - assets/logo/icon.png

    - assets/GoogleG.png

    - assets/audio/Coffee_Break_Music.mp3
    - assets/audio/Credit_Sound.mp3
    - assets/audio/Extended_Sound.mp3
    - assets/audio/Fail.mp3
    - assets/audio/Game_Play.mp3
    - assets/audio/Ghost_Normal_Move.mp3
    - assets/audio/Ghost_Return_To_Home.mp3
    - assets/audio/Ghost_Turn_To_Blue.mp3
    - assets/audio/Pacman_Eating_Dots_While_Turning_The_Corner.mp3
    - assets/audio/Pacman_Eating_Dots.mp3
    - assets/audio/Pacman_Eating_The_Fruit.mp3
    - assets/audio/Pacman_Eating_The_Ghost.mp3
    - assets/audio/Spurt_Move_1.mp3
    - assets/audio/Spurt_Move_2.mp3
    - assets/audio/Spurt_Move_3.mp3
    - assets/audio/Spurt_Move_4.mp3
    - assets/audio/Start_Music.mp3
    - assets/audio/Home_Music.mp3

    - assets/game/map/map.png
    - assets/game/pacman.png

    - assets/game/characters/pacman/up/pacman_up_0.png
    - assets/game/characters/pacman/up/pacman_up_1.png
    - assets/game/characters/pacman/up/pacman_up_2.png
    - assets/game/characters/pacman/left/pacman_left_0.png
    - assets/game/characters/pacman/left/pacman_left_1.png
    - assets/game/characters/pacman/left/pacman_left_2.png
    - assets/game/characters/pacman/right/pacman_right_0.png
    - assets/game/characters/pacman/right/pacman_right_1.png
    - assets/game/characters/pacman/right/pacman_right_2.png
    - assets/game/characters/pacman/down/pacman_down_0.png
    - assets/game/characters/pacman/down/pacman_down_1.png
    - assets/game/characters/pacman/down/pacman_down_2.png
    - assets/game/characters/pacman/idle/pacman_idle_0.png
    - assets/game/characters/pacman/death/pacman_death_0.png
    - assets/game/characters/pacman/death/pacman_death_1.png
    - assets/game/characters/pacman/death/pacman_death_2.png
    - assets/game/characters/pacman/death/pacman_death_3.png
    - assets/game/characters/pacman/death/pacman_death_4.png
    - assets/game/characters/pacman/death/pacman_death_5.png
    - assets/game/characters/pacman/death/pacman_death_6.png
    - assets/game/characters/pacman/death/pacman_death_7.png
    - assets/game/characters/pacman/death/pacman_death_8.png
    - assets/game/characters/pacman/death/pacman_death_9.png
    - assets/game/characters/pacman/death/pacman_death_10.png
    - assets/game/characters/pacman/death/pacman_death_11.png

    - assets/game/characters/blinky/up/blinky_up_0.png
    - assets/game/characters/blinky/up/blinky_up_1.png
    - assets/game/characters/blinky/left/blinky_left_0.png
    - assets/game/characters/blinky/left/blinky_left_1.png
    - assets/game/characters/blinky/right/blinky_right_0.png
    - assets/game/characters/blinky/right/blinky_right_1.png
    - assets/game/characters/blinky/down/blinky_down_0.png
    - assets/game/characters/blinky/down/blinky_down_1.png
    - assets/game/characters/blinky/frightened0/blinky_frightened0_0.png
    - assets/game/characters/blinky/frightened0/blinky_frightened0_1.png
    - assets/game/characters/blinky/frightened0/blinky_frightened0_2.png
    - assets/game/characters/blinky/frightened0/blinky_frightened0_3.png
    - assets/game/characters/blinky/frightened1/blinky_frightened1_0.png
    - assets/game/characters/blinky/frightened1/blinky_frightened1_1.png
    - assets/game/characters/blinky/frightened1/blinky_frightened1_2.png
    - assets/game/characters/blinky/frightened1/blinky_frightened1_3.png
    - assets/game/characters/blinky/eatenUp/blinky_eatenUp_0.png
    - assets/game/characters/blinky/eatenLeft/blinky_eatenLeft_0.png
    - assets/game/characters/blinky/eatenRight/blinky_eatenRight_0.png
    - assets/game/characters/blinky/eatenDown/blinky_eatenDown_0.png

    - assets/game/characters/pinky/up/pinky_up_0.png
    - assets/game/characters/pinky/up/pinky_up_1.png
    - assets/game/characters/pinky/left/pinky_left_0.png
    - assets/game/characters/pinky/left/pinky_left_1.png
    - assets/game/characters/pinky/right/pinky_right_0.png
    - assets/game/characters/pinky/right/pinky_right_1.png
    - assets/game/characters/pinky/down/pinky_down_0.png
    - assets/game/characters/pinky/down/pinky_down_1.png
    - assets/game/characters/pinky/frightened0/pinky_frightened0_0.png
    - assets/game/characters/pinky/frightened0/pinky_frightened0_1.png
    - assets/game/characters/pinky/frightened0/pinky_frightened0_2.png
    - assets/game/characters/pinky/frightened0/pinky_frightened0_3.png
    - assets/game/characters/pinky/frightened1/pinky_frightened1_0.png
    - assets/game/characters/pinky/frightened1/pinky_frightened1_1.png
    - assets/game/characters/pinky/frightened1/pinky_frightened1_2.png
    - assets/game/characters/pinky/frightened1/pinky_frightened1_3.png
    - assets/game/characters/pinky/eatenUp/pinky_eatenUp_0.png
    - assets/game/characters/pinky/eatenLeft/pinky_eatenLeft_0.png
    - assets/game/characters/pinky/eatenRight/pinky_eatenRight_0.png
    - assets/game/characters/pinky/eatenDown/pinky_eatenDown_0.png

    - assets/game/characters/inky/up/inky_up_0.png
    - assets/game/characters/inky/up/inky_up_1.png
    - assets/game/characters/inky/left/inky_left_0.png
    - assets/game/characters/inky/left/inky_left_1.png
    - assets/game/characters/inky/right/inky_right_0.png
    - assets/game/characters/inky/right/inky_right_1.png
    - assets/game/characters/inky/down/inky_down_0.png
    - assets/game/characters/inky/down/inky_down_1.png
    - assets/game/characters/inky/frightened0/inky_frightened0_0.png
    - assets/game/characters/inky/frightened0/inky_frightened0_1.png
    - assets/game/characters/inky/frightened0/inky_frightened0_2.png
    - assets/game/characters/inky/frightened0/inky_frightened0_3.png
    - assets/game/characters/inky/frightened1/inky_frightened1_0.png
    - assets/game/characters/inky/frightened1/inky_frightened1_1.png
    - assets/game/characters/inky/frightened1/inky_frightened1_2.png
    - assets/game/characters/inky/frightened1/inky_frightened1_3.png
    - assets/game/characters/inky/eatenUp/inky_eatenUp_0.png
    - assets/game/characters/inky/eatenLeft/inky_eatenLeft_0.png
    - assets/game/characters/inky/eatenRight/inky_eatenRight_0.png
    - assets/game/characters/inky/eatenDown/inky_eatenDown_0.png

    - assets/game/characters/clyde/up/clyde_up_0.png
    - assets/game/characters/clyde/up/clyde_up_1.png
    - assets/game/characters/clyde/left/clyde_left_0.png
    - assets/game/characters/clyde/left/clyde_left_1.png
    - assets/game/characters/clyde/right/clyde_right_0.png
    - assets/game/characters/clyde/right/clyde_right_1.png
    - assets/game/characters/clyde/down/clyde_down_0.png
    - assets/game/characters/clyde/down/clyde_down_1.png
    - assets/game/characters/clyde/frightened0/clyde_frightened0_0.png
    - assets/game/characters/clyde/frightened0/clyde_frightened0_1.png
    - assets/game/characters/clyde/frightened0/clyde_frightened0_2.png
    - assets/game/characters/clyde/frightened0/clyde_frightened0_3.png
    - assets/game/characters/clyde/frightened1/clyde_frightened1_0.png
    - assets/game/characters/clyde/frightened1/clyde_frightened1_1.png
    - assets/game/characters/clyde/frightened1/clyde_frightened1_2.png
    - assets/game/characters/clyde/frightened1/clyde_frightened1_3.png
    - assets/game/characters/clyde/eatenUp/clyde_eatenUp_0.png
    - assets/game/characters/clyde/eatenLeft/clyde_eatenLeft_0.png
    - assets/game/characters/clyde/eatenRight/clyde_eatenRight_0.png
    - assets/game/characters/clyde/eatenDown/clyde_eatenDown_0.png

    - assets/game/bonuses/cherry.png
    - assets/game/bonuses/strawberry.png
    - assets/game/bonuses/orange.png
    - assets/game/bonuses/apple.png
    - assets/game/bonuses/melon.png
    - assets/game/bonuses/galaxian.png
    - assets/game/bonuses/bell.png
    - assets/game/bonuses/key.png

  fonts:
    - family: PacFont
      fonts:
        - asset: assets/fonts/PacFont.ttf
    
    - family: PressStart
      fonts:
        - asset: assets/fonts/PressStart.ttf

    - family: BJCree
      fonts:
        - asset: assets/fonts/BJCree-Regular.ttf
        - asset: assets/fonts/BJCree-Bold.ttf
          weight: 700
        - asset: assets/fonts/BJCree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BJCree-Medium.ttf
          weight: 500
        